### ISSUE TITLE
\functions\bc_rewards\end\uh_houston_we_have_a_problem

### ISSUE THREAD

**Issue by SunSerega** [DmitryRendov/blazeandcave-advancements-pack#11]
Выдаёт ракеты которые не стакаются с остальными, надо добавить данные как у обычных ракет на длительность 1

**Comment by SunSerega** [comment]
[fixed](https://github.com/DmitryRendov/blazeandcave-advancements-pack/commit/df1c89987b5dd0cc4d5ffe114b9978303dfcf026)

**Comment by DmitryRendov** [comment]
Create a PR please to master @SunSerega
